### ISSUE TITLE
Is this a verbatim copy of my sources?

### ISSUE THREAD

**Issue by vktr** [bbougot/torrent.NET#1]
Hello!

This seems like a verbatim copy of most (if not all) of my source code here, https://github.com/vktr/libtorrent-net.

What is the purpose of copying my sources and promoting them as "self made"?

![image](https://cloud.githubusercontent.com/assets/1491824/23703046/43de6f74-03fe-11e7-887e-04472c741d1d.png)

**Comment by bbougot** [comment]
Appologies for the misunderstanding. I have actually forked your repository, updated a piece of code and not included your licence. It is indeed a lack of credit to your original work. I will recreate the repository from a fork of your sources and update my readme on Popcorn. I let you decide if I can still use your project as a libtorrent-based wrapper. Sorry again!

**Comment by vktr** [comment]
Hello! I didn't mean to come off as cranky.

Let me add a license to my repository, then you can fork and make your changes according to that license. Also, hit me up on viktor@viktorelofsson.se if you want to talk further on working together to get the wrapper working with the latest sources and also fix file seeking and so on 😄 There are some pretty cool ways to accomplish that.

**Comment by bbougot** [comment]
No problem! I will wait for you to add your licence and I will come back to you soon ;) Many thanks!
